### ISSUE TITLE
Improve hydra configuration file structure and dependencies.

### ISSUE THREAD

**Issue by ezeeEric** [ezeeEric/DiVAE#10]
- The initial hierarchical structure of the config files is not yet optimal. There is still duplication and unused options defined across models. I will need to think some more on how to do this elegantly.
- The calo models are not yet working due to the same reason. Will open a new issue for that.
- How to specify user dependent inputs/options?
- How to have a dependency between models and tasks?

**Comment by abhishekabhishek** [comment]
***Does activation_fct belong in config ?***

Due to the already large hyper-parameter space, it might be beneficial to fix the non-linearity function (maybe as a global variable in the network initialization methods). We seldom compare performance across non-linear functions.

ReLU is a good default choice since its properties are well studied and the other alternatives (tanh, sigmoid) are often sigmoidal and suffer from vanishing gradients so not suitable for deep architectures.

**Comment by ezeeEric** [comment]
I think it's best to make this a private, fixed variable of each model. The code uses ReLU for all models except the discrete VAE, which uses tanh [see here](https://github.com/QuadrantAI/dvae/blob/cadd9a15aeeef5dab51b07a4073e1c4e42cab4d3/nets.py#L59). Will remove it from the config.
