### ISSUE TITLE
Bring run.py to top directory level

### ISSUE THREAD

**Issue by abhishekabhishek** [ezeeEric/DiVAE#4]
- Minor issue but need to source source.me each session
- Would be easier and cleaner to have run.py at the top directory level (/DiVAE) instead of (/DiVAE/scripts) and call the different submodules from there - dataloader, modelMaker etc.

**Comment by ezeeEric** [comment]
Reason for this choice was the possibility of having multiple run scripts doing different things and keeping the top level directory decluttered.
Note that the hydra-configuration file path in the decorator will need to be changed (removing the `../`).

**Comment by abhishekabhishek** [comment]
What might we need multiple run scripts for ? Would it make sense to have all the tasks defined in a single file and then select specific tasks using config ?

**Comment by ezeeEric** [comment]
An example would be separate `runMNIST` and a `runCALO` scripts, if it turns out, that routines cannot be split nicely between different datasets. That was the initial idea, but with the recent developments on the data handling and unification, this should be covered... So feel free to move it a level up.

Note that I am running `source.me` to attach the package path to my `PYTHONPATH` environment variable. This will need to be done regardless where `run.py` is located, at least to my knowledge.

**Comment by abhishekabhishek** [comment]
Sounds good. I believe you won't need to run source.me if you call the interpreter from the package path (i.e. the top directory level)

**Comment by ezeeEric** [comment]
With this update the code execution will then be restricted to the top-level directory, i.e. you could not execute the script from an outside/inside directory. The imports would need to be made relative (`from . import xyz`), when you do not append to `PYTHONPATH`. 
So overall, I am not entirely sure this will make handling easier and cleaner.
